### ISSUE TITLE
It seems Reflux cannot use reflux-promise for the whole application

### ISSUE THREAD

**Issue by pengux** [reflux/reflux-promise#11]
In my React app, I set Reflux to use reflux-promise with browser's Promise implementation just before `ReactDOM.render`. But still, in my action files, it throws the error:

```
Uncaught TypeError: ConnectionActions.create.listenAndPromise is not a function
```

**Comment by vcarel** [comment]
I had a similar issue. Look at your imports order... did you enable Reflux-Promise _before_ importing your stores / actions ?

**Comment by pengux** [comment]
This was a while ago and I'm not sure about the issue anymore so closing this.

**Comment by philsturgeon** [comment]
We're currently getting this issue, and are stuck in a situation where we cannot update react from 0.14 to 15.3.

The README suggests doing this once in our application bootstrapper, but doing this leaves us with `_permissionActions2.default.fetch.promise is not a function`. 

We tried adding the setup to the failing store as well to see if that would solve or move the error, but no change.

```
# permissionStore.js
import Reflux from 'reflux';
import RefluxPromise from "reflux-promise";

// Uses the user agent's Promise implementation
Reflux.use(RefluxPromise(window.Promise));
```

So, any ideas where to go from here? I can help with debugging if you need more information. Trying this with Reflux 0.3.1 and 0.4.1, same issue.
