### ISSUE TITLE
NPM registry serves 1.0.2 package with incorrect content

### ISSUE THREAD

**Issue by lassebm** [reflux/reflux-promise#13]
NPM registry URL: http://registry.npmjs.org/reflux-promise/-/reflux-promise-1.0.2.tgz

The `index.js` in this package doesn't contain the changes from commit 6d14b9d65cfc6a82132986cd53311ab72b0d793a which were committed just before the 1.0.2 version bump in commit 6213844a530c41495cb6082a6e9d9b39573eecf0.

**Comment by dotted** [comment]
+1

**Comment by LarsTimm** [comment]
+1

**Comment by spoike** [comment]
1.0.4 should resolve this issue now.
