### ISSUE TITLE
window.Promise is undefined in IE10 

### ISSUE THREAD

**Issue by yinxiangbo** [reflux/reflux-promise#21]
when i debugged in IE10，got the “window.Promise” undefined error in the following  statement

Reflux.use(RefluxPromise(window.Promise))

**Comment by devinivy** [comment]
You can pass any A+ compliant promise implementation to `RefluxPromise()`.  For `window.Promise` to work you would need to include a polyfill for the browser first.  Check out https://github.com/stefanpenner/es6-promise for one such option.
